# Generated by Django 4.2.4 on 2023-08-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
